# Generated by Django 5.0.2 on 2024-02-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0005_alter_userprofile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='photo_as_blob',
        ),
    ]
