# Generated by Django 5.0.2 on 2024-02-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0008_contactprofile_contactnumber_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='source',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
